# Generated by Django 3.2 on 2021-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_author_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
