# Generated by Django 3.2 on 2021-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210413_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
